# Generated by Django 2.2.2 on 2019-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190706_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedb',
            name='description',
            field=models.CharField(choices=[('video', 'VIDIO'), ('audio', 'AUDIO'), ('file', 'FILE'), ('pdf', 'PDF')], default='file', max_length=6),
        ),
    ]
