# Generated by Django 2.2.2 on 2019-07-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190706_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedb',
            name='author',
        ),
    ]
