# Generated by Django 2.2.1 on 2019-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('writer', models.CharField(max_length=44)),
            ],
        ),
    ]
