# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-07 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_scrap',
            new_name='last_scrape',
        ),
    ]
