# Generated by Django 2.2.1 on 2019-05-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
    ]
