# Generated by Django 2.0.2 on 2019-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(default='nothing'),
        ),
    ]
